import '../styles/globals.css';
import LayoutWithSideBar from "@/components/Layout/LayoutWithSideBar";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: 'Food Tracker',
	description: 'Generated by create next app',
	keywords: 'Food Truck, food, city, UOC, TFM'
};

type Props = {
	children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
	return (
		<html lang="en">
		<body>
		<UserProvider>
			<LayoutWithSideBar>
				{children}
			</LayoutWithSideBar>
		</UserProvider>
		</body>
		</html>
	);
}
